create database customer_behaviourr

use customer_behaviourr

select * from customer_behaviourr

1.What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer_behaviourr
group by gender

2.which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_behaviourr
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_behaviourr)

3.which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as "Average Product Rating"
from customer_behaviourr
group by item_purchased
order by avg(review_rating) desc
limit 5;

4.COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING
select shipping_type,
round(avg(purchase_amount),2)
from customer_behaviourr
where shipping_type in ('Standard','Express')
group by shipping_type


5.DO SUBSCRIBED CUSTOMERS SPEND MORE? COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON_SUBSCRIBERS.
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_behaviourr
group by subscription_status
order by total_revenue, avg_spend desc;

6.WHICH 5 PRODUCTS HAVE THE HIGHEST PERCENTAGE OF PURCHASES WITH DISCOUNT APPLIED?
select item_purchased,
round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_behaviourr
group by item_purchased
order by discount_rate desc
limit 5;

7.What are the top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_behaviourr
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

8.are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_behaviourr
where previous_purchases > 5
group by subscription_status

9.what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_behaviourr
group by age_group
order by total_revenue desc;